name: 'Read KeyVault Secrets'
description: "Reads secret from specified keyvault"
author: 'Joergen and Robin'

inputs:
  secretNames:
    description: 'Commaseparated list of secrets to read'
    required: true
  keyvaultName:
    description: 'Name of keyvault to read from'
    required: true
  keyvaultCreds:
    description: 'The credentials for the keyvault service principal'
    required: true
    default: ${{ secrets.MIN_KEYVAULT_CCOE_KV01 }}

branding:
  color: 'purple'
  icon: check-circle

runs:
  using: composite

  steps:
  - uses: actions/checkout@v2
  - uses: Azure/login@v1
    with:
      creds: ${{ inputs.keyvaultCreds }}
  - uses: Azure/get-keyvault-secrets@v1
    with: 
      keyvault: '${{ inputs.keyvaultName }}'
      secrets: '${{ inputs.secretNames }}'
    id: keyvault

outputs:
  secrets:
    description: "Contains the secrets requested"
    value: ${{ steps.keyvault.outputs }}
